var define,
    amd,
    exports,
    module,
    Ticle,
    SimpleTimer,
    WorkerThread,
    recordDiff,
    WorkerTimer,
    MozBlobBuilder,
    __esModule,
    action,
    data,
    id,
    delay,
    args,
    options,
    WorkerThreadTimer,
    MSBlobBuilder,
    // setTimeout,
    // setInterval,
    setTrustyInterval,
    // clearTimeout,
    // clearInterval,
    TimerCtor,
    clearTrustyInterval;

